modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL = "https://github.com/TheResimulators/Sim-U-Kraft-Resimulated-1.15/issues"
license = "Insert License here"

[[mods]]
modId="simukraft"
version="${file.jarVersion}"
displayName="Sim-u-Kraft"
credits="Resimulators" #optional
authors="Aidie8, Fabbe50, Mcboy, Reprevise" #optional
description='''This mod is a remake of the original simukraft. it was updated to 1.7.10 and now being updated to 1.15'''

[[dependencies.suk]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.suk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
